### ISSUE TITLE
Better authentication error reporting

### ISSUE THREAD

**Issue by admytren** [midokura/python-midonetclient#15]
Need to improve authentication error reporting. CLI uses username, password, and project_id to authenticate. If any of those are incorrect, then the user will receive "Internal error: WWW-Authenticate" message even after entering one of the commands requiring authentication.

It would be much nicer to have a clear error message, like:
- Authentication Error: Please check your username and password
- Authentication Error: Please check your project_id

Additionally, first authentication check should be performed when launching CLI and not while running commands.

**Comment by tomoe** [comment]
The error "Internal error: WWW-Authenticate" was caused by the API server bug, which has been fixed. closing...
