### ISSUE TITLE
CLI utility naming

### ISSUE THREAD

**Issue by admytren** [midokura/python-midonetclient#16]
This is very subjective. I was wondering if it would be okay to rename midonet CLI wrapper so it has a more descriptive name. Right now it's called "mn-ctl", which may imply that it's similar to ovs-ctl or mm-ctl utilities. What do you think about calling it "midonet-cli"?

**Comment by gontanon** [comment]
+1

**Comment by tomoe** [comment]
+1

**Comment by 0cjs** [comment]
I don't recall if the program also accepts arguments on the command line to tell it what to do in lieu of starting an interactive interpreter. If it does, adding 'ctl' or 'c' on the end seems a bit more appropriate to me, to match, e.g., ntpdc(1).

```
$ ntpdc -n -p
     remote           local      st poll reach  delay   offset    disp
=======================================================================
=130.54.208.201  192.168.96.33    3  128  377 0.01657  0.004161 0.06091
=157.7.135.233   192.168.96.33    2  128  377 0.01299 -0.002949 0.05933
=91.189.89.199   192.168.96.33    2  128  377 0.27199  0.002708 0.05730
*59.106.180.168  192.168.96.33    2  128  377 0.00482  0.005453 0.05292
=211.125.120.31  192.168.96.33    2  128  377 0.01566  0.005557 0.05151
$
```

versus

```
$ ntpdc -n
ntpdc> peers
     remote           local      st poll reach  delay   offset    disp
=======================================================================
=130.54.208.201  192.168.96.33    3  128  377 0.01657  0.004161 0.06091
=157.7.135.233   192.168.96.33    2  128  377 0.01299 -0.002949 0.05933
=91.189.89.199   192.168.96.33    2  128  377 0.27199  0.002708 0.05730
*59.106.180.168  192.168.96.33    2  128  377 0.00482  0.005453 0.05292
=211.125.120.31  192.168.96.33    2  128  377 0.01566  0.005557 0.05151
ntpdc> quit
$ 
```

**Comment by gontanon** [comment]
We have an option for that, but it works the opposite way. By default you get a prompt, -e will 'eval' a command taken from the argument list and return.

**Comment by 0cjs** [comment]
Works the same way, actually; "-p" is not to give you a prompt, but to do the "peers" command. Anyway, "-cli" seems a bit funny to me given that it can also be used like the "-ctl" commands in non-cli mode, but I'm not actually all that fussed about it. "-ctl" does seem reasonable to me if it works just like the ovs-*ctl commands, but simply has the addition of an interactive mode if you don't give it a command. That would probably mean removing the need for '-e' when you run it with a command from the command line.

**Comment by admytren** [comment]
Hi Curt.

I believe the intention of this utility is to be interactive. For example, all of the syntax help and command auto-completion is only available in the interactive mode. The batch mode is there for convenience. From my experience with this tool it is much more of a "cli" utility and a very difficult to use "ctl" utility.

Sincerely,
Artem Dmytrenko

**Comment by tomoe** [comment]
Closing as the fix has been merged.
